name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Conda Environment
      run: |
        conda env create -f environment.yml
        conda init
        conda activate vonMises

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
        cd ..
        python install.py

    - name: Code Lint
      run: |
        ruff version
        ruff format --check .
        ruff check --output-format=github .
