name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: vonMises
        environment-file: environment.yml

    - name: Initialize Conda
      run: |
        /usr/share/miniconda/bin/conda init bash
        eval "$(/usr/share/miniconda/bin/conda shell.bash hook)"

    - name: Activate Conda environment
      run: conda activate vonMises

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .
        cd ..
        python install.py

    - name: Code Lint
      run: |
        ruff version
        ruff format --check .
        ruff check --output-format=github .
